services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
    networks:
      - public-network
    volumes:
      - './frontend/nginx.conf:/etc/nginx/conf.d/default.conf'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - '3000'
    # set dependency with mongo
    # connect backend container with frontend container
    # connect backend container with mongo container
    networks:
      - public-network

  mongo:
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    networks:
      - private-network
    ports:
      - '27017'

# Define networks
networks:
  public-network:
  private-network:

# Define volumes
volumes:
  mongo_data:
